//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzayTepeSiteYonetimi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SiteDBEntities2 : DbContext
    {
        public SiteDBEntities2()
            : base("name=SiteDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<S_Kisiler_Result> S_Kisiler(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Kisiler_Result>("S_Kisiler", iDParameter);
        }
    
        public virtual ObjectResult<S_Bloklar_Result> S_Bloklar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Bloklar_Result>("S_Bloklar");
        }
    
        public virtual ObjectResult<S_Daireler_Result> S_Daireler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Daireler_Result>("S_Daireler");
        }
    
        public virtual ObjectResult<S_Odemeler_Result> S_Odemeler(Nullable<int> kisiID)
        {
            var kisiIDParameter = kisiID.HasValue ?
                new ObjectParameter("KisiID", kisiID) :
                new ObjectParameter("KisiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Odemeler_Result>("S_Odemeler", kisiIDParameter);
        }
    
        public virtual ObjectResult<S_OdemeTipi_Result> S_OdemeTipi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_OdemeTipi_Result>("S_OdemeTipi");
        }
    
        public virtual int UDI_Kisi(Nullable<int> islemTipi, Nullable<int> iD, string adiSoyadi, Nullable<int> blokAdiID, Nullable<int> daireAdiID, Nullable<bool> kiraciEvsahibi, Nullable<System.DateTime> kayitTarihi, Nullable<System.DateTime> daireGirisTarihi, Nullable<System.DateTime> daireCikisTarihi, Nullable<bool> oturuyorAyrildi, string notlar)
        {
            var islemTipiParameter = islemTipi.HasValue ?
                new ObjectParameter("IslemTipi", islemTipi) :
                new ObjectParameter("IslemTipi", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var adiSoyadiParameter = adiSoyadi != null ?
                new ObjectParameter("AdiSoyadi", adiSoyadi) :
                new ObjectParameter("AdiSoyadi", typeof(string));
    
            var blokAdiIDParameter = blokAdiID.HasValue ?
                new ObjectParameter("BlokAdiID", blokAdiID) :
                new ObjectParameter("BlokAdiID", typeof(int));
    
            var daireAdiIDParameter = daireAdiID.HasValue ?
                new ObjectParameter("DaireAdiID", daireAdiID) :
                new ObjectParameter("DaireAdiID", typeof(int));
    
            var kiraciEvsahibiParameter = kiraciEvsahibi.HasValue ?
                new ObjectParameter("KiraciEvsahibi", kiraciEvsahibi) :
                new ObjectParameter("KiraciEvsahibi", typeof(bool));
    
            var kayitTarihiParameter = kayitTarihi.HasValue ?
                new ObjectParameter("KayitTarihi", kayitTarihi) :
                new ObjectParameter("KayitTarihi", typeof(System.DateTime));
    
            var daireGirisTarihiParameter = daireGirisTarihi.HasValue ?
                new ObjectParameter("DaireGirisTarihi", daireGirisTarihi) :
                new ObjectParameter("DaireGirisTarihi", typeof(System.DateTime));
    
            var daireCikisTarihiParameter = daireCikisTarihi.HasValue ?
                new ObjectParameter("DaireCikisTarihi", daireCikisTarihi) :
                new ObjectParameter("DaireCikisTarihi", typeof(System.DateTime));
    
            var oturuyorAyrildiParameter = oturuyorAyrildi.HasValue ?
                new ObjectParameter("OturuyorAyrildi", oturuyorAyrildi) :
                new ObjectParameter("OturuyorAyrildi", typeof(bool));
    
            var notlarParameter = notlar != null ?
                new ObjectParameter("Notlar", notlar) :
                new ObjectParameter("Notlar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDI_Kisi", islemTipiParameter, iDParameter, adiSoyadiParameter, blokAdiIDParameter, daireAdiIDParameter, kiraciEvsahibiParameter, kayitTarihiParameter, daireGirisTarihiParameter, daireCikisTarihiParameter, oturuyorAyrildiParameter, notlarParameter);
        }
    
        public virtual int UDI_OdemeEkle(Nullable<int> isDeleted, Nullable<int> kisiID, Nullable<int> kayitID, Nullable<System.DateTime> tarih, Nullable<int> odemeTipiID, Nullable<decimal> tutar, string aciklama)
        {
            var isDeletedParameter = isDeleted.HasValue ?
                new ObjectParameter("IsDeleted", isDeleted) :
                new ObjectParameter("IsDeleted", typeof(int));
    
            var kisiIDParameter = kisiID.HasValue ?
                new ObjectParameter("KisiID", kisiID) :
                new ObjectParameter("KisiID", typeof(int));
    
            var kayitIDParameter = kayitID.HasValue ?
                new ObjectParameter("KayitID", kayitID) :
                new ObjectParameter("KayitID", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var odemeTipiIDParameter = odemeTipiID.HasValue ?
                new ObjectParameter("OdemeTipiID", odemeTipiID) :
                new ObjectParameter("OdemeTipiID", typeof(int));
    
            var tutarParameter = tutar.HasValue ?
                new ObjectParameter("Tutar", tutar) :
                new ObjectParameter("Tutar", typeof(decimal));
    
            var aciklamaParameter = aciklama != null ?
                new ObjectParameter("Aciklama", aciklama) :
                new ObjectParameter("Aciklama", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDI_OdemeEkle", isDeletedParameter, kisiIDParameter, kayitIDParameter, tarihParameter, odemeTipiIDParameter, tutarParameter, aciklamaParameter);
        }
    
        public virtual ObjectResult<S_OdemelerSablon_Result> S_OdemelerSablon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_OdemelerSablon_Result>("S_OdemelerSablon");
        }
    
        public virtual int UDI_Borclandir(Nullable<int> kisiID, Nullable<int> odemeTipiID, Nullable<decimal> tutar, Nullable<System.DateTime> vadeTarihi)
        {
            var kisiIDParameter = kisiID.HasValue ?
                new ObjectParameter("KisiID", kisiID) :
                new ObjectParameter("KisiID", typeof(int));
    
            var odemeTipiIDParameter = odemeTipiID.HasValue ?
                new ObjectParameter("OdemeTipiID", odemeTipiID) :
                new ObjectParameter("OdemeTipiID", typeof(int));
    
            var tutarParameter = tutar.HasValue ?
                new ObjectParameter("Tutar", tutar) :
                new ObjectParameter("Tutar", typeof(decimal));
    
            var vadeTarihiParameter = vadeTarihi.HasValue ?
                new ObjectParameter("VadeTarihi", vadeTarihi) :
                new ObjectParameter("VadeTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UDI_Borclandir", kisiIDParameter, odemeTipiIDParameter, tutarParameter, vadeTarihiParameter);
        }
    }
}
