//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzayTepeSiteYonetimi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SiteDBEntities2 : DbContext
    {
        public SiteDBEntities2()
            : base("name=SiteDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<S_Kisiler_Result> S_Kisiler(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Kisiler_Result>("S_Kisiler", iDParameter);
        }
    
        public virtual ObjectResult<S_Bloklar_Result> S_Bloklar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Bloklar_Result>("S_Bloklar");
        }
    
        public virtual ObjectResult<S_Daireler_Result> S_Daireler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Daireler_Result>("S_Daireler");
        }
    
        public virtual ObjectResult<S_Odemeler_Result> S_Odemeler(Nullable<int> kisiID)
        {
            var kisiIDParameter = kisiID.HasValue ?
                new ObjectParameter("KisiID", kisiID) :
                new ObjectParameter("KisiID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_Odemeler_Result>("S_Odemeler", kisiIDParameter);
        }
    
        public virtual ObjectResult<S_OdemeTipi_Result> S_OdemeTipi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<S_OdemeTipi_Result>("S_OdemeTipi");
        }
    }
}
